//! This file is automatically generated by Zitron from input grammar
//! source file "src/edn/edn.zy".
//!
//! Parser for EDN notation
const tokenize = @import("tokenize.zig");
const Token = tokenize.Token;
const Tokenizer = tokenize.Tokenizer;

const types = @import("types.zig");
const Atom = types.Atom;
const Map = types.Map;
const List = types.List;
const Vector = types.Vector;
const Set = types.Set;
const Form = types.Form;
const FormCons = types.FormCons;
const Pair = types.Pair;
const Tagged = types.Tagged;
const Forms = std.ArrayList(Form);

const Allocator = std.mem.Allocator;

/// Collects the forms at the end of the parse.
const ParseContext = struct {
    forms: []Form,

    pub fn format(pc: *const ParseContext, writer: *std.Io.Writer) !void {
        for (pc.forms) |form| {
            try writer.print("{f}\n", .{form});
        }
    }

    pub fn deinit(pc: *ParseContext, allocator: Allocator) void {
        for (pc.forms) |form| {
            form.deinit(allocator);
        }
        allocator.free(pc.forms);
    }
};

fn freeSet(set: *Set, allocator: Allocator) void {
    const keys = set.keys();
    for (keys) |form| {
        form.deinit(allocator);
    }
    set.deinit(allocator);
    allocator.destroy(set);
}

fn freeMap(map: *Map, allocator: Allocator) void {
    var iter = map.iterator();
    while (iter.next()) |entry| {
        entry.key_ptr.deinit(allocator);
        entry.value_ptr.deinit(allocator);
    }
    map.deinit(allocator);
    allocator.destroy(map);
}

// #line 68 src/edn/edn.zig
// zig fmt: off
// **************** End of %include directives **********************************
// zig fmt: off

const std = @import("std");
const builtin = @import("builtin");

const NDEBUG = builtin.mode != .Debug;

/// This specifies the token enum.  If generated separately this is an import of
///  that file.
/// ***************** Begin token definitions ***********************************
pub const TokenKind = enum(u5) {
    end_of_input = 0,
    PAL,
    PAR,
    CRL,
    CRR,
    SQL,
    SQR,
    LSET,
    TAGGED,
    DISCARD,
    SYMBOL,
    NUMBER,
    STRING,
    KEYWORD,
    CHARACTER,
    NIL,
    TRUE,
    FALSE,
};
// **************** End token definitions ***************************************
// The next sections is a series of constant definitions dictating
// various aspects of the generated parser.
//
//    YYCODETYPE         is the data type used to store the integer codes
//                       that represent terminal and non-terminal symbols.
//                       "unsigned char" is used if there are fewer than
//                       256 symbols.  Larger types otherwise.
//    YYNOCODE           is a number of type YYCODETYPE that is not used for
//                       any terminal or nonterminal symbol.
//    YYFALLBACK         If defined, this indicates that one or more tokens
//                       (also known as: "terminal symbols") have fall-back
//                       values which should be used if the original symbol
//                       would not parse.  This permits keywords to sometimes
//                       be used as identifiers, for example.
//    YYACTIONTYPE       is the data type used for "action codes" - numbers
//                       that indicate what to do in response to the next
//                       token.
//    YY_TOKEN_TYPE     is the data type used for minor type for terminal
//                       symbols.  Background: A "minor type" is a semantic
//                       value associated with a terminal or non-terminal
//                       symbols.  For example, for an "ID" terminal symbol,
//                       the minor type might be the name of the identifier.
//                       Each non-terminal can have a different minor type.
//                       Terminal symbols all have the same minor type, though.
//                       This macros defines the minor type for terminal
//                       symbols.
//    YYMINORTYPE        is the data type used for all minor types.
//                       This is typically a union of many types, one of
//                       which is YY_TOKEN_TYPE.  The entry in the union
//                       for terminal symbols is called `@"Token"`.
//    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
//                       zero the stack is dynamically sized using realloc()
//    ParseARG_SDECL     A static variable declaration for the %extra_argument
//    ParseARG_PDECL     A parameter declaration for the %extra_argument
//    ParseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
//    ParseARG_STORE     Code to store %extra_argument into yypParser
//    ParseARG_FETCH     Code to extract %extra_argument from yypParser
//    ParseCTX_*         As ParseARG_ except for %extra_context
//    YYREALLOC          Name of the realloc() function to use
//    YYFREE             Name of the free() function to use
//    YYDYNSTACK         True if stack space should be extended on heap
//    YYERRORSYMBOL      is the code number of the error symbol.  If not
//                       defined, then do no error processing.
//    YYNSTATE           the combined number of states.
//    YYNRULE            the number of rules in the grammar
//    YYNTOKEN           Number of terminal symbols
//    YY_MAX_SHIFT       Maximum value for shift actions
//    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
//    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
//    YY_ERROR_ACTION    The yy_action[] code for syntax error
//    YY_ACCEPT_ACTION   The yy_action[] code for accept
//    YY_NO_ACTION       The yy_action[] code for no-op
//    YY_MIN_REDUCE      Minimum value for reduce actions
//    YY_MAX_REDUCE      Maximum value for reduce actions
//    YY_MIN_DSTRCTR     Minimum symbol value that has a destructor
//    YY_MAX_DSTRCTR     Maximum symbol value that has a destructor
//
// ************* Begin constants *****************************************
const YYCODETYPE = u8;
const YYNOCODE = 36;
const YYACTIONTYPE = u8;
const YY_HASWILDCARD = false;
const YYWILDCARD: void = {};
const YY_TOKEN_TYPE = Token;
pub const YYMINORTYPE = minor: {
    @setRuntimeSafety(false);
    break :minor union {
        @"Token": YY_TOKEN_TYPE,
        @"*Set": *Set,
        @"*Vector": *Vector,
        @"?*FormCons": ?*FormCons,
        @"*Atom": *Atom,
        @"?Form": ?Form,
        @"Form": Form,
        @"?*Pair": ?*Pair,
        @"[]Form": []Form,
        @"*Forms": *Forms,
        @"*Map": *Map,
    };
};
const YYSTACKDEPTH = 256;
const YYHAS_ERRORSYMBOL = false;
const YY_TRACE = false;
const YYFALLBACK = false;
const YYNSTATE =             16;
const YYNRULE =              50;
const YYNRULE_WITH_ACTION =  39;
const YYNTOKEN =             18;
const YY_MAX_SHIFT =         15;
const YY_MIN_SHIFTREDUCE =   64;
const YY_MAX_SHIFTREDUCE =   113;
const YY_ERROR_ACTION =      114;
const YY_ACCEPT_ACTION =     115;
const YY_NO_ACTION =         116;
const YY_MIN_REDUCE =        117;
const YY_MAX_REDUCE =        166;
const YY_MIN_DSTRCTR =       18;
const YY_MAX_DSTRCTR =       35;
// ************* End constants *******************************************

const YY_VOIDTOKEN = @TypeOf(YY_TOKEN_TYPE) == void;

const YY_NLOOKAHEAD = yy_lookahead.len;

/// Set a value for zitron_no_error_recovery to disable error recovery.
const YYNOERRORRECOVERY = @hasDecl(@This(), "zitron_no_error_recovery");

/// Set a value for zitron_track_max_stack_depth to track the maximum stack depth on the Parser instance.
const YYTRACKMAXSTACKDEPTH = @hasDecl(@This(), "zitron_track_max_stack_depth");

/// Set a value for zitron_coverage to enable coverage tracing.
const YYCOVERAGE = @hasDecl(@This(), "zitron_coverage");

const yyTracePrompt = if (@hasDecl(@This(), "zitron_trace_prompt")) @This().zitron_trace_prompt else "";

// Next are the tables used to determine what action to take based on the
// current state and lookahead token.  These tables are used to implement
// functions that take a state number and lookahead value and return an
// action integer.
//
// Suppose the action integer is N.  Then the action is determined as
// follows
//
//   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
//                                      token onto the stack and goto state N.
//
//   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
//     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
//
//   N == YY_ERROR_ACTION               A syntax error has occurred.
//
//   N == YY_ACCEPT_ACTION              The parser accepts its input.
//
//   N == YY_NO_ACTION                  No such action.  Denotes unused
//                                      slots in the yy_action[] table.
//
//   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
//     and YY_MAX_REDUCE
//
// The action table is constructed as a single large table named yy_action[].
// Given state S and lookahead X, the action is computed as either:
//
//    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
//    (B)   N = yy_default[S]
//
// The (A) formula is preferred.  The B formula is used instead if
// yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
//
// The formulas above are for computing the action when the lookahead is
// a terminal symbol.  If the lookahead is a non-terminal (as occurs after
// a reduce action) then the yy_reduce_ofst[] array is used in place of
// the yy_shift_ofst[] array.
//
// The following are the tables generated in this section:
//
//  yy_action[]        A single table containing all actions.
//  yy_lookahead[]     A table containing the lookahead for each entry in
//                     yy_action.  Used to detect hash collisions.
//  yy_shift_ofst[]    For each state, the offset into yy_action for
//                     shifting terminals.
//  yy_reduce_ofst[]   For each state, the offset into yy_action for
//                     shifting non-terminals after a reduce.
//  yy_default[]       Default action for each state.
//
// *********** Begin parsing tables **********************************************/
const YY_ACTTAB_COUNT = 388;
// zig fmt: off
const yy_action: [YY_ACTTAB_COUNT]YYACTIONTYPE  = .{
  116,    5,  116,    1,   77,    3,   74,    2,   13,   11, //     0
   96,   97,   98,   99,  100,  101,  102,  102,    5,  116, //    10
    1,   81,    3,  116,    2,   13,   11,   96,   97,   98, //    20
   99,  100,  101,  102,  102,    5,  116,    1,  116,    3, //    30
   79,    2,   13,   11,   96,   97,   98,   99,  100,  101, //    40
  102,  102,    5,  116,    1,   76,    3,  116,    2,   13, //    50
   11,   96,   97,   98,   99,  100,  101,  102,  102,    5, //    60
   75,    1,  116,    3,  116,    2,   13,   11,   96,   97, //    70
   98,   99,  100,  101,  102,  102,    5,  116,    1,   80, //    80
    3,  116,    2,   13,   11,   96,   97,   98,   99,  100, //    90
  101,  102,  102,    5,  116,    1,  116,    3,   78,    2, //   100
   13,   11,   96,   97,   98,   99,  100,  101,  102,  102, //   110
  117,    5,  116,    1,  116,    3,  116,    2,   13,   11, //   120
   96,   97,   98,   99,  100,  101,  102,  102,    5,  116, //   130
    1,  116,    3,  116,    2,   13,   11,   96,   97,   98, //   140
   99,  100,  101,  102,  102,    5,  116,    1,  116,    3, //   150
  116,    2,   13,  116,   96,   97,   98,   99,  100,  101, //   160
  102,  102,    5,  116,    1,  116,    3,  116,    2,  116, //   170
   11,   96,   97,   98,   99,  100,  101,  102,  102,    5, //   180
  116,    1,  116,    3,  116,    2,  116,  116,   96,   97, //   190
   98,   99,  100,  101,  102,  102,  116,  115,    9,  119, //   200
  125,  120,  122,  121,  123,  116,  116,  116,  126,  124, //   210
   10,   10,   10,   10,   10,  116,  116,  116,  146,   10, //   220
  116,  143,    4,   10,  148,  125,  120,  122,  121,  123, //   230
  116,    7,  116,  126,  124,  141,  125,  120,  122,  121, //   240
  123,    8,  116,  116,  126,  124,   10,   10,   10,   10, //   250
   10,  116,  116,  116,  146,   10,  116,  142,  116,   10, //   260
    6,  125,  120,  122,  121,  123,  116,  116,   15,  126, //   270
  124,    6,  125,  120,  122,  121,  123,  116,  116,  138, //   280
  126,  124,  147,  125,  120,  122,  121,  123,  116,  116, //   290
  116,  126,  124,  140,  125,  120,  122,  121,  123,  116, //   300
  116,  116,  126,  124,  118,  125,  120,  122,  121,  123, //   310
  116,  116,  116,  126,  124,  144,  144,  144,  144,  144, //   320
  116,  116,  116,   12,  144,  116,  116,  116,  144,  137, //   330
  125,  120,  122,  121,  123,  116,  116,  116,  126,  124, //   340
  145,  145,  145,  145,  145,  116,  116,  116,  116,  145, //   350
  116,  116,  116,  145,  135,  135,  135,  135,  135,  116, //   360
  116,  116,   14,  136,  136,  136,  136,  136,  135,  116, //   370
  116,  116,  116,  116,  116,  116,  116,  136, //   380
};
const yy_lookahead: [406]YYCODETYPE = .{
   36,    1,   36,    3,    4,    5,    2,    7,    8,    9, //     0
   10,   11,   12,   13,   14,   15,   16,   17,    1,   36, //    10
    3,    4,    5,   36,    7,    8,    9,   10,   11,   12, //    20
   13,   14,   15,   16,   17,    1,   36,    3,   36,    5, //    30
    6,    7,    8,    9,   10,   11,   12,   13,   14,   15, //    40
   16,   17,    1,   36,    3,    4,    5,   36,    7,    8, //    50
    9,   10,   11,   12,   13,   14,   15,   16,   17,    1, //    60
    2,    3,   36,    5,   36,    7,    8,    9,   10,   11, //    70
   12,   13,   14,   15,   16,   17,    1,   36,    3,    4, //    80
    5,   36,    7,    8,    9,   10,   11,   12,   13,   14, //    90
   15,   16,   17,    1,   36,    3,   36,    5,    6,    7, //   100
    8,    9,   10,   11,   12,   13,   14,   15,   16,   17, //   110
    0,    1,   36,    3,   36,    5,   36,    7,    8,    9, //   120
   10,   11,   12,   13,   14,   15,   16,   17,    1,   36, //   130
    3,   36,    5,   36,    7,    8,    9,   10,   11,   12, //   140
   13,   14,   15,   16,   17,    1,   36,    3,   36,    5, //   150
   36,    7,    8,   36,   10,   11,   12,   13,   14,   15, //   160
   16,   17,    1,   36,    3,   36,    5,   36,    7,   36, //   170
    9,   10,   11,   12,   13,   14,   15,   16,   17,    1, //   180
   36,    3,   36,    5,   36,    7,   36,   36,   10,   11, //   190
   12,   13,   14,   15,   16,   17,   36,   18,   19,   20, //   200
   21,   22,   23,   24,   25,   36,   36,   36,   29,   30, //   210
   21,   22,   23,   24,   25,   36,   36,   36,   29,   30, //   220
   36,   32,   33,   34,   20,   21,   22,   23,   24,   25, //   230
   36,   27,   36,   29,   30,   20,   21,   22,   23,   24, //   240
   25,   26,   36,   36,   29,   30,   21,   22,   23,   24, //   250
   25,   36,   36,   36,   29,   30,   36,   32,   36,   34, //   260
   20,   21,   22,   23,   24,   25,   36,   36,   28,   29, //   270
   30,   20,   21,   22,   23,   24,   25,   36,   36,   28, //   280
   29,   30,   20,   21,   22,   23,   24,   25,   36,   36, //   290
   36,   29,   30,   20,   21,   22,   23,   24,   25,   36, //   300
   36,   36,   29,   30,   20,   21,   22,   23,   24,   25, //   310
   36,   36,   36,   29,   30,   21,   22,   23,   24,   25, //   320
   36,   36,   36,   29,   30,   36,   36,   36,   34,   20, //   330
   21,   22,   23,   24,   25,   36,   36,   36,   29,   30, //   340
   21,   22,   23,   24,   25,   36,   36,   36,   36,   30, //   350
   36,   36,   36,   34,   21,   22,   23,   24,   25,   36, //   360
   36,   36,   29,   21,   22,   23,   24,   25,   35,   36, //   370
   36,   36,   36,   36,   36,   36,   36,   35, //   380
   18,   18,   18,   18,   18,   18,   18,   18,   18,   18, //   388
   18,   18,   18,   18,   18,   18,   18,   18, //   398
};
const YY_SHIFT_COUNT =    15;
const YY_SHIFT_MIN =      0;
const YY_SHIFT_MAX =      188;
const yy_shift_ofst: [16]u16 = .{
  137,    0,   17,   34,   51,   68,  137,   85,  102,  120, //     0
  137,  137,  154,  171,  188,    4, //    10
};
const YY_REDUCE_COUNT = 14;
const YY_REDUCE_MIN =   0;
const YY_REDUCE_MAX =   352;
const yy_reduce_ofst: [15]i16  = .{
  189,  199,  214,  225,  235,  250,  261,  272,  283,  294, //     0
  304,  319,  329,  343,  352, //    10
};
const yy_default: [16]YYACTIONTYPE = .{
  114,  114,  114,  114,  114,  114,  139,  114,  114,  114, //     0
  114,  114,  114,  114,  114,  114, //    10
};
// /********** End of zitron-generated parsing tables *****************************/
//
// The next table maps tokens (terminal symbols) into fallback tokens.
// If a construct like the following:
//
//      %fallback ID X Y Z.
//
// appears in the grammar, then ID becomes a fallback token for X, Y,
// and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
// but it does not parse, the type of the token is changed to ID and
// the parse is retried before an error is thrown.
//
// This feature can be used, for example, to cause some keywords in a language
// to revert to identifiers if they keyword does not apply in the context where
// it appears.
//
const yyFallback = [_]YYCODETYPE{
};

/// The following structure represents a single element of the
/// parser's stack.  Information stored includes:
///
///   +  The state number for the parser at this level of the stack.
///
///   +  The value of the token stored at this level of the stack.
///      (In other words, the "major" token.)
///
///   +  The semantic value stored at this level of the stack.  This is
///      the information used by the action routines in the grammar.
///      It is sometimes called the "minor" token.
///
/// After the "shift" half of a SHIFTREDUCE action, the yy_stateno field
/// actually contains the reduce action for the second half of the
/// SHIFTREDUCE.
const YyStackEntry = struct {
    /// The state-number, or reduce action in SHIFTREDUCE.
    stateno: YYACTIONTYPE,
    /// The major token value.  This is the code number for the token at this stack level.
    major: YYCODETYPE,
    /// The user-supplied minor token value.  This is the value of the token.
    minor: YYMINORTYPE,
};

/// This value is the minimum amount of memory needed to build the
/// parser stack.
pub const parser_stack_minimum = @sizeOf(Parser) + (@sizeOf(YyStackEntry) * YYSTACKDEPTH);

/// The state of the parser is completely contained in an instance of
/// the following structure.
pub const Parser = struct {
    /// Allocator
    allocator: std.mem.Allocator,
    /// Pointer to top element of the stack
    tos: [*]YyStackEntry,
    //
    // TODO: reckon with `yyhwm`
    //
    /// Shifts left before out of the error
    errcnt: isize,

    result: ParseContext,
    stack_end: [*]YyStackEntry,
    stack: [*]YyStackEntry,
    stk0: []YyStackEntry,

    /// Create a Parser on the heap, returning a pointer to it.
    /// Free later with `destroy`.
    pub fn create(allocator: std.mem.Allocator , result: ParseContext) std.mem.Allocator.Error!*Parser {
        var yypParser = try allocator.create(Parser);
        yypParser.result = result;
        try yypParser.init(allocator, result);
        return yypParser;
    }

    /// Free all Parser memory, including the *Parser itself.
    pub fn destroy(yypParser: *Parser) void {
        yypParser.deinit();
        yypParser.allocator.destroy(yypParser);
    }

    /// Allocate a stack for the Parser and set all fields to their
    /// initial state.  No need to call this if using `create`.  Free later
    /// with `deinit`.
    pub fn init(yypParser: *Parser, allocator: std.mem.Allocator , result: ParseContext) std.mem.Allocator.Error!void {
        yypParser.result = result;
        yypParser.allocator = allocator;
        yypParser.stk0 = try yypParser.allocator.alloc(YyStackEntry, 100);
        yypParser.stack = yypParser.stk0.ptr;
        yypParser.stack_end = yypParser.stack + (yypParser.stk0.len - 1);
        yypParser.errcnt = -1; // TODO: Deal with NOERRORRECOVERY
        yypParser.tos = yypParser.stack;
        yypParser.stack[0].stateno = 0;
        yypParser.stack[0].major = 0;
        yypParser.stack[0].minor = undefined; // This is ok
    }

    /// Free the stack memory of the parser, first destroying anything
    /// left on the stack.
    pub fn deinit(yypParse: *Parser) void {
        yypParse.reset();
        yypParse.allocator.free(yypParse.stk0);
    }

    /// Call this when there are no tokens remaining.
    pub fn finalize(yypParse: *Parser ) !void {
        // Undefined is ok here, it can't be captured and no
        // destructor will ever be called on it, as determined
        // by the 'major type', .end_of_input.
        try yypParse.parse(.end_of_input, undefined );
    }

    // NOTE: this code is somewhat oddly organized due to being translated from
    // C.  The following will appear as ordinary member functions in the type:

    /// Reset the parser to a known-good state, freeing any
    /// destructable data kept on the parsing stack.  Retains
    /// the parser stack allocation, to free it, call `deinit`,
    /// or just `destroy` if the parser itself is heap-allocated.
    pub const reset = yy_parse_reset;

    /// Parse a token.
    pub const parse = yyParse;
};

// For tracing shifts, the names of all terminals and nonterminals
// are required.  The following table supplies these names.
pub const yyTokenName = [_][:0]const u8{
   "$",          //    0
   "PAL",        //    1
   "PAR",        //    2
   "CRL",        //    3
   "CRR",        //    4
   "SQL",        //    5
   "SQR",        //    6
   "LSET",       //    7
   "TAGGED",     //    8
   "DISCARD",    //    9
   "SYMBOL",     //   10
   "NUMBER",     //   11
   "STRING",     //   12
   "KEYWORD",    //   13
   "CHARACTER",  //   14
   "NIL",        //   15
   "TRUE",       //   16
   "FALSE",      //   17
   "edn",        //   18
   "forms",      //   19
   "form",       //   20
   "atom",       //   21
   "list",       //   22
   "vector",     //   23
   "map",        //   24
   "set",        //   25
   "v_forms",    //   26
   "s_forms",    //   27
   "l_forms",    //   28
   "discard",    //   29
   "tagged",     //   30
   "boolean",    //   31
   "pair",       //   32
   "pairs",      //   33
   "m_form",     //   34
   "t_form",     //   35
};
// For tracing reduce actions, the names of all rules are required.
//
pub const yyRuleName = [_][:0]const u8{
    "edn ::= forms", //   0
    "forms ::= forms form", //   1
    "forms ::= form", //   2
    "form ::= list", //   3
    "form ::= map", //   4
    "form ::= vector", //   5
    "form ::= set", //   6
    "form ::= tagged", //   7
    "form ::= atom", //   8
    "form ::= discard", //   9
    "list ::= PAL l_forms PAR", //  10
    "list ::= PAL PAR", //  11
    "map ::= CRL pairs CRR", //  12
    "map ::= CRL CRR", //  13
    "vector ::= SQL v_forms SQR", //  14
    "vector ::= SQL SQR", //  15
    "set ::= LSET s_forms CRR", //  16
    "set ::= LSET CRR", //  17
    "tagged ::= TAGGED t_form", //  18
    "tagged ::= TAGGED discard t_form", //  19
    "discard ::= DISCARD form", //  20
    "l_forms ::= form l_forms", //  21
    "l_forms ::= form", //  22
    "v_forms ::= v_forms form", //  23
    "v_forms ::= form", //  24
    "pairs ::= pairs pair", //  25
    "pairs ::= pair", //  26
    "pair ::= m_form m_form", //  27
    "pair ::= m_form discard m_form", //  28
    "pair ::= discard", //  29
    "s_forms ::= s_forms form", //  30
    "s_forms ::= form", //  31
    "atom ::= SYMBOL", //  32
    "atom ::= NUMBER", //  33
    "atom ::= STRING", //  34
    "atom ::= KEYWORD", //  35
    "atom ::= CHARACTER", //  36
    "atom ::= NIL", //  37
    "atom ::= TRUE|FALSE", //  38
    "m_form ::= list", //  39
    "m_form ::= map", //  40
    "m_form ::= vector", //  41
    "m_form ::= set", //  42
    "m_form ::= tagged", //  43
    "m_form ::= atom", //  44
    "t_form ::= list", //  45
    "t_form ::= map", //  46
    "t_form ::= vector", //  47
    "t_form ::= set", //  48
    "t_form ::= atom", //  49
};


/// Try to increase the size of the parser stack.  Throws if the allocation
/// fails.
fn yyGrowStack(yy_p: *Parser) !void {
    const yy_new_size = yy_p.stk0.len * 2 + 100;
    const yy_idx = (@intFromPtr(yy_p.tos) - @intFromPtr(yy_p.stack));
    const yyp_new = try yy_p.allocator.realloc(yy_p.stk0, yy_new_size);
    yy_p.stack = yyp_new.ptr;
    yy_p.stk0 = yyp_new;
    yy_p.tos = yyp_new.ptr + yy_idx;
    yy_p.stack_end = yyp_new.ptr + (yy_new_size - 1);
}


/// The following function deletes the "minor type" or semantic value
/// associated with a symbol.  The symbol can be either a terminal
/// or nonterminal. "yymajor" is the symbol code, and "yypminor" is
/// a pointer to the value to be deleted.  The code used to do the
/// deletions is derived from the %destructor and/or %token_destructor
/// directives of the input grammar.
///
fn yy_destructor(
  yypParser: *Parser,    // The parser */
  yymajor: YYCODETYPE,     // Type code for object to destroy */
  yypminor: *YYMINORTYPE,   // The object to be destroyed */
) void {

    var result = yypParser.result; _ = .{&result};
    defer {

        yypParser.result = result;
    }
    _ = .{ yypminor }; // Unused variable ward
    const allocator = yypParser.allocator; _ = .{allocator};
    switch( yymajor ){
        // Here is inserted the actions which take place when a
        // terminal or non-terminal is destroyed.  This can happen
        // when the symbol is popped from the stack during a
        // reduce or during error processing or when a parser is
        // being destroyed before it is finished parsing.
        //
        // Note: during a reduce, the only symbols destroyed are those
        // which appear on the RHS of the rule, but which are *not* used
        // inside the C code.
        //
//******** Begin destructor definitions ***************************************/
        18, // edn
        => {
// #line 78 src/edn/edn.zy
 for ((yypminor.@"[]Form")) |form| form.deinit(allocator);
// #line 639 src/edn/edn.zig
        },
        19, // forms
        => {
// #line 81 src/edn/edn.zy

    for ((yypminor.@"*Forms").items) |form| form.deinit(allocator);
    (yypminor.@"*Forms").deinit(allocator);
    allocator.destroy((yypminor.@"*Forms"));

// #line 649 src/edn/edn.zig
        },
        20, // form
        29, // discard
        => {
// #line 88 src/edn/edn.zy
 if ((yypminor.@"?Form")) |form| form.deinit(allocator);
// #line 656 src/edn/edn.zig
        },
        21, // atom
        22, // list
        23, // vector
        24, // map
        25, // set
        30, // tagged
        34, // m_form
        35, // t_form
        => {
// #line 91 src/edn/edn.zy
 (yypminor.@"Form").deinit(allocator);
// #line 669 src/edn/edn.zig
        },
        26, // v_forms
        => {
// #line 106 src/edn/edn.zy

    for ((yypminor.@"*Vector").items) |form| form.deinit(allocator);
    (yypminor.@"*Vector").deinit(allocator);
    allocator.destroy((yypminor.@"*Vector"));

// #line 679 src/edn/edn.zig
        },
        27, // s_forms
        => {
// #line 113 src/edn/edn.zy
 freeSet((yypminor.@"*Set"), allocator);
// #line 685 src/edn/edn.zig
        },
        28, // l_forms
        => {
// #line 116 src/edn/edn.zy
 if ((yypminor.@"?*FormCons")) |f_cons| f_cons.deinit(allocator);
// #line 691 src/edn/edn.zig
        },
        31, // boolean
        => {
// #line 125 src/edn/edn.zy
 (yypminor.@"*Atom").destroy(allocator);
// #line 697 src/edn/edn.zig
        },
        32, // pair
        => {
// #line 128 src/edn/edn.zy
 if ((yypminor.@"?*Pair")) |pair| pair.destroy(allocator);
// #line 703 src/edn/edn.zig
        },
        33, // pairs
        => {
// #line 131 src/edn/edn.zy
 freeMap((yypminor.@"*Map"), allocator);
// #line 709 src/edn/edn.zig
        },
//******** End destructor definitions *****************************************/
        else =>  {},   // If no destructor action specified: do nothing */
    }
}

const yy_assert = std.debug.assert;

///
/// Pop the parser's stack once.
///
/// If there is a destructor routine associated with the token which
/// is popped from the stack, then call it.
fn yy_pop_parser_stack(yypParser: *Parser) void {
    yy_assert(@intFromPtr(yypParser.tos) > @intFromPtr(yypParser.stack));
    var yytos = yypParser.tos;
    yypParser.tos -= 1;
    if (comptime !NDEBUG) {

    }
    yy_destructor(yypParser, yytos[0].major, &yytos[0].minor);
}


///
/// Clear all secondary memory allocations from the parser
///
fn yy_parse_reset(yypParser: *Parser) void {
    var yytos = yypParser.tos;
    while (@intFromPtr(yytos) > @intFromPtr(yypParser.stack)) {
        if (comptime !NDEBUG) {

        }
        if (yytos[0].major >= YY_MIN_DSTRCTR) {
            yy_destructor(yypParser, yytos[0].major, &yytos[0].minor);
        }
        yytos -= 1;
    }
}

// TODO: deal with this stuff
//
// /*
// ** Return the peak depth of the stack for a parser.
// */
// #ifdef YYTRACKMAXSTACKDEPTH
// int ParseStackPeak(void *p){
//   Parser *pParser = (Parser*)p;
//   return pParser->yyhwm;
// }
// #endif

/// This array of booleans keeps track of the parser statement
/// coverage.  The element yycoverage[X][Y] is set when the parser
/// is in state X and has a lookahead token Y.  In a well-tested
/// systems, every element of this matrix should end up being set.
threadlocal var yycoverage: (if (YYCOVERAGE)
                                [YYNSTATE][YYNTOKEN]bool
                            else
                                void) = if (YYCOVERAGE)
                                           .{ .{false} ** YYNTOKEN } ** YYNSTATE
                                        else {};

//// Write into `out` a description of every state/lookahead combination that
///
///   (1)  has not been used by the parser, and
///   (2)  is not a syntax error.
///
/// Return the number of missed state/lookahead combinations.
pub fn yyParseCoverage(yy_out: anytype, yy_print: bool) !usize {
    if (comptime !YYCOVERAGE) @compileError("define `zitron_coverage` in %include/%code to enable coverage.");
    var yy_nmissed: usize = 0;
    for (0..YYNSTATE) |yy_stateno| {
        const yy_i = yy_shift_ofst[yy_stateno];
        for (0..YYNTOKEN) |yy_ilookahead| {
            // This means a syntax error, so we don't care:
            if (yy_lookahead[yy_i + yy_ilookahead] != yy_ilookahead) continue;
            const yy_missed = yycoverage[yy_stateno][yy_ilookahead];
            if (yy_missed) yy_nmissed += 1;
            if (yy_print) {
                try yy_out.print("State {d} lookahead {s} {s}\n",
                .{yy_stateno, yyTokenName[yy_ilookahead], if (yy_missed) "ok" else "missed",},);
            }
        }
    }
    return yy_nmissed;
}

/// Find the appropriate action for a parser given the terminal
/// look-ahead token yy_ilookahead.
fn yy_find_shift_action(
    /// The look-ahead token
    yy_ilookahead: YYCODETYPE,
    /// Current state number
    yy_stateno: YYACTIONTYPE,
) YYACTIONTYPE {
    if (yy_stateno > YY_MAX_SHIFT) return yy_stateno;
    yy_assert(yy_stateno <= YY_SHIFT_COUNT);
    if (comptime YYCOVERAGE) {
        yycoverage[yy_stateno][yy_ilookahead] = true;
    }
    var yy_ilook = yy_ilookahead;
    while (true) {
        var yy_i = yy_shift_ofst[yy_stateno];
        yy_assert(yy_i >= 0);
        yy_assert(yy_i <= YY_ACTTAB_COUNT);
        yy_assert(yy_i+YYNTOKEN <= YY_NLOOKAHEAD);
        yy_assert(yy_ilook != YYNOCODE);
        yy_assert(yy_ilook < YYNTOKEN);
        yy_i += yy_ilook;
        yy_assert(yy_i < YY_NLOOKAHEAD);
        if (yy_lookahead[yy_i] != yy_ilook) {
            if (comptime YYFALLBACK) {
                yy_assert(yy_ilook < yyFallback.len);
                const iFallback: YYCODETYPE = yyFallback[yy_ilook];
                if (iFallback != 0) {
                    if (comptime !NDEBUG) {

                    }
                    yy_assert(yyFallback[iFallback] == 0) ; // Fallback loop must terminate */
                    yy_ilook = iFallback;
                    continue;
                }
            }
            if (comptime YY_HASWILDCARD) {
                const j: YYCODETYPE = yy_i - yy_ilook + YYWILDCARD;
                yy_assert(j < yy_lookahead.len);
                if (yy_lookahead[j] == YYWILDCARD and yy_ilook > 0) {
                    if (comptime !NDEBUG) {

                    }
                    return yy_action[j];
                }
            }
            return yy_default[yy_stateno];
        } else {
            yy_assert(yy_i < yy_action.len);
            return yy_action[yy_i];
        }
    }
}


/// Find the appropriate action for a parser given the non-terminal
/// look-ahead token yy_lookahead.
fn yy_find_reduce_action(
    /// Current state number
    yy_stateno: YYACTIONTYPE ,
    /// The look-ahead token
    yy_ilookahead: YYCODETYPE ,
) YYACTIONTYPE {
    if (comptime YYHAS_ERRORSYMBOL) {
        if (yy_stateno > YY_REDUCE_COUNT) {
          return yy_default[yy_stateno];
        }
    } else {
      yy_assert(yy_stateno <= YY_REDUCE_COUNT);
    }
    var yy_i: isize = yy_reduce_ofst[yy_stateno];
    yy_assert(yy_ilookahead != YYNOCODE);
    yy_i += yy_ilookahead;
    if (comptime YYHAS_ERRORSYMBOL) {
        if (yy_i < 0 or yy_i >= YY_ACTTAB_COUNT or yy_lookahead[@intCast(yy_i)] != yy_lookahead) {
            return yy_default[yy_stateno];
        }
    } else {
        yy_assert( yy_i >= 0 and yy_i < YY_ACTTAB_COUNT );
        yy_assert( yy_lookahead[@intCast(yy_i)]==yy_ilookahead );
    }
    return yy_action[@intCast(yy_i)];
}

/// The following routine is called if the stack overflows.
fn yyStackOverflow(yypParser: *Parser) !void {

    var result = yypParser.result; _ = .{&result};
    defer {

        yypParser.result = result;
    }
    if (comptime !NDEBUG) {

    }
    while (@intFromPtr(yypParser.tos) > @intFromPtr(yypParser.stack)) yy_pop_parser_stack(yypParser);
    // Here code is inserted which will execute if the parser
    // stack ever overflows.
    { // This lets us re-throw:
//******* Begin %stack_overflow code ******************************************/
//******* End %stack_overflow code ********************************************/
    }
}

///
/// Print tracing information for a SHIFT action
fn yyTraceShift(yypParser: *Parser, yyNewState: usize, zTag: []const u8) void {
    if (comptime false) {
        _ = .{yypParser, yyNewState, zTag};
    }
    if (comptime !NDEBUG) {

    }
}

inline fn yy_sint(i: anytype) @Type(.{ .int = .{
    .bits = @typeInfo(@TypeOf(i)).int.bits + 1,
    .signedness = .signed,
} }) {
    if (@typeInfo(@TypeOf(i)).int.signedness == .signed) {
        @compileError("Value is already a signed type");
    }
    return @intCast(i);
}

/// Perform a shift action.
fn yy_shift(
    /// The parser to be shifted
    yypParser: *Parser,
    /// The new state to shift in
    yyNewState: YYACTIONTYPE,
    /// The major token to shift in
    yyMajor: YYCODETYPE,
    /// The minor token to shift in
    yyMinor: YY_TOKEN_TYPE,
) !void {
    yypParser.tos += 1;
    // #ifdef YYTRACKMAXSTACKDEPTH
    //     if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    //     yypParser->yyhwm++;
    //     yy_assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
    //     }
    // #endif
    var yytos = yypParser.tos;
    var yy_new = yyNewState;
    if (@intFromPtr(yytos) > @intFromPtr(yypParser.stack_end)) {
        yyGrowStack(yypParser) catch  {
            yypParser.tos -= 1;
            try yyStackOverflow(yypParser);
            return;
        };
        yytos = yypParser.tos;
        yy_assert(@intFromPtr(yytos) <= @intFromPtr(yypParser.stack_end));
    }
    if (yy_new > YY_MAX_SHIFT) {
        yy_new += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
    }
    yytos[0].stateno = yy_new;
    yytos[0].major = yyMajor;
    yytos[0].minor.@"Token" = yyMinor;
    yyTraceShift(yypParser, yy_new, "Shift");
}

/// For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
/// of that rule */
const yyRuleInfoLhs: []const YYCODETYPE = &.{
    18,  // (0) edn ::= forms
    19,  // (1) forms ::= forms form
    19,  // (2) forms ::= form
    20,  // (3) form ::= list
    20,  // (4) form ::= map
    20,  // (5) form ::= vector
    20,  // (6) form ::= set
    20,  // (7) form ::= tagged
    20,  // (8) form ::= atom
    20,  // (9) form ::= discard
    22,  // (10) list ::= PAL l_forms PAR
    22,  // (11) list ::= PAL PAR
    24,  // (12) map ::= CRL pairs CRR
    24,  // (13) map ::= CRL CRR
    23,  // (14) vector ::= SQL v_forms SQR
    23,  // (15) vector ::= SQL SQR
    25,  // (16) set ::= LSET s_forms CRR
    25,  // (17) set ::= LSET CRR
    30,  // (18) tagged ::= TAGGED t_form
    30,  // (19) tagged ::= TAGGED discard t_form
    29,  // (20) discard ::= DISCARD form
    28,  // (21) l_forms ::= form l_forms
    28,  // (22) l_forms ::= form
    26,  // (23) v_forms ::= v_forms form
    26,  // (24) v_forms ::= form
    33,  // (25) pairs ::= pairs pair
    33,  // (26) pairs ::= pair
    32,  // (27) pair ::= m_form m_form
    32,  // (28) pair ::= m_form discard m_form
    32,  // (29) pair ::= discard
    27,  // (30) s_forms ::= s_forms form
    27,  // (31) s_forms ::= form
    21,  // (32) atom ::= SYMBOL
    21,  // (33) atom ::= NUMBER
    21,  // (34) atom ::= STRING
    21,  // (35) atom ::= KEYWORD
    21,  // (36) atom ::= CHARACTER
    21,  // (37) atom ::= NIL
    21,  // (38) atom ::= TRUE|FALSE
    34,  // (39) m_form ::= list
    34,  // (40) m_form ::= map
    34,  // (41) m_form ::= vector
    34,  // (42) m_form ::= set
    34,  // (43) m_form ::= tagged
    34,  // (44) m_form ::= atom
    35,  // (45) t_form ::= list
    35,  // (46) t_form ::= map
    35,  // (47) t_form ::= vector
    35,  // (48) t_form ::= set
    35,  // (49) t_form ::= atom
};

// TODO: is a 128 symbol RHS arbitrary? I mean it is but, in a bad way?
// more seems nuts

/// For rule J, yyRuleInfoNRhs[J] contains the negative of the number
/// of symbols on the right-hand side of that rule.
const yyRuleInfoNRhs: []const i8 = &.{
   -1,  // (0) edn ::= forms
   -2,  // (1) forms ::= forms form
   -1,  // (2) forms ::= form
   -1,  // (3) form ::= list
   -1,  // (4) form ::= map
   -1,  // (5) form ::= vector
   -1,  // (6) form ::= set
   -1,  // (7) form ::= tagged
   -1,  // (8) form ::= atom
   -1,  // (9) form ::= discard
   -3,  // (10) list ::= PAL l_forms PAR
   -2,  // (11) list ::= PAL PAR
   -3,  // (12) map ::= CRL pairs CRR
   -2,  // (13) map ::= CRL CRR
   -3,  // (14) vector ::= SQL v_forms SQR
   -2,  // (15) vector ::= SQL SQR
   -3,  // (16) set ::= LSET s_forms CRR
   -2,  // (17) set ::= LSET CRR
   -2,  // (18) tagged ::= TAGGED t_form
   -3,  // (19) tagged ::= TAGGED discard t_form
   -2,  // (20) discard ::= DISCARD form
   -2,  // (21) l_forms ::= form l_forms
   -1,  // (22) l_forms ::= form
   -2,  // (23) v_forms ::= v_forms form
   -1,  // (24) v_forms ::= form
   -2,  // (25) pairs ::= pairs pair
   -1,  // (26) pairs ::= pair
   -2,  // (27) pair ::= m_form m_form
   -3,  // (28) pair ::= m_form discard m_form
   -1,  // (29) pair ::= discard
   -2,  // (30) s_forms ::= s_forms form
   -1,  // (31) s_forms ::= form
   -1,  // (32) atom ::= SYMBOL
   -1,  // (33) atom ::= NUMBER
   -1,  // (34) atom ::= STRING
   -1,  // (35) atom ::= KEYWORD
   -1,  // (36) atom ::= CHARACTER
   -1,  // (37) atom ::= NIL
   -1,  // (38) atom ::= TRUE|FALSE
   -1,  // (39) m_form ::= list
   -1,  // (40) m_form ::= map
   -1,  // (41) m_form ::= vector
   -1,  // (42) m_form ::= set
   -1,  // (43) m_form ::= tagged
   -1,  // (44) m_form ::= atom
   -1,  // (45) t_form ::= list
   -1,  // (46) t_form ::= map
   -1,  // (47) t_form ::= vector
   -1,  // (48) t_form ::= set
   -1,  // (49) t_form ::= atom
};

/// Perform a reduce action and the shift that must immediately
/// follow the reduce.
///
/// The yyLookahead and yyLookaheadToken parameters provide reduce actions
/// access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
/// if the lookahead token has already been consumed.  As this procedure is
/// only called from one place, optimizing compilers will in-line it, which
/// means that the extra parameters have no performance impact.
fn yy_reduce(
    /// The parser
    yypParser: *Parser,
    /// Number of the rule by which to reduce
    yyruleno: usize,
    /// Lookahead token, or YYNOCODE if none
    yyLookahead: YYCODETYPE,
    /// Value of the lookahead token */
    yyLookaheadToken: YY_TOKEN_TYPE
) !YYACTIONTYPE {

    var result = yypParser.result; _ = .{&result};
    defer {

        yypParser.result = result;
    }
    _ = .{yyruleno, yyLookahead, yyLookaheadToken};
    var yymsp = yypParser.tos;
    const allocator = yypParser.allocator; _ = .{allocator};
    var yylhsminor: YYMINORTYPE = undefined; _ = .{&yylhsminor};
    const yysize = yyRuleInfoNRhs[yyruleno];
    errdefer {
        // If user code throws, we trim the stack, including
        // where the reduced action was supposed to go.  Destructors
        // run either before the user action, or deferred.
        yymsp = yymsp  - @abs(yysize);
        yypParser.tos = yymsp;
    }
    switch( yyruleno ){
    // Beginning here are the reduction cases.  A typical example
    // follows:
    //   0,
    //  #line <lineno> <grammarfile>
    //     => { ... },           // User supplied code
    //  #line <lineno> <thisfile>
    //
//********* Begin reduce actions **********************************************/
        0, // edn ::= forms
        => {
// #line 0 src/edn/edn.zy
            // #line 204 src/edn/edn.zy

            yylhsminor.@"[]Form" = try (yymsp - 1)[1].minor.@"*Forms".toOwnedSlice(allocator);
            result.forms = yylhsminor.@"[]Form";
            (yymsp - 1)[1].minor.@"*Forms".deinit(allocator);
            allocator.destroy((yymsp - 1)[1].minor.@"*Forms");
// #line 1128 src/edn/edn.zig
            (yymsp - 1)[1].minor.@"[]Form" = yylhsminor.@"[]Form";
        },
        1, // forms ::= forms form
        => {
// #line 0 src/edn/edn.zy
            // #line 211 src/edn/edn.zy

            if ((yymsp - 1)[1].minor.@"?Form") |form| {
            errdefer form.deinit(allocator);
            try (yymsp - 2)[1].minor.@"*Forms".append(allocator, form);
            }
// #line 1141 src/edn/edn.zig
        },
        2, // forms ::= form
        => {
// #line 0 src/edn/edn.zy
            // #line 218 src/edn/edn.zy

            errdefer if ((yymsp - 1)[1].minor.@"?Form") |form| form.deinit(allocator);
            var forms: *Forms = try allocator.create(Forms);
            forms.* = .empty;
            errdefer allocator.destroy(forms);
            if ((yymsp - 1)[1].minor.@"?Form") |form| {
            try forms.append(allocator, form);
            }
            yylhsminor.@"*Forms" = forms;
// #line 1157 src/edn/edn.zig
            (yymsp - 1)[1].minor.@"*Forms" = yylhsminor.@"*Forms";
        },
        3, // form ::= list
        => {
// #line 0 src/edn/edn.zy
            // #line 229 src/edn/edn.zy

            (yymsp - 1)[1].minor.@"?Form" = (yymsp - 1)[1].minor.@"Form"; // F-overwrites-L
// #line 1167 src/edn/edn.zig
        },
        4, // form ::= map
        => {
// #line 0 src/edn/edn.zy
            // #line 233 src/edn/edn.zy

            (yymsp - 1)[1].minor.@"?Form" = (yymsp - 1)[1].minor.@"Form"; // F-overwrites-M
// #line 1176 src/edn/edn.zig
        },
        5, // form ::= vector
        => {
// #line 0 src/edn/edn.zy
            // #line 237 src/edn/edn.zy

            (yymsp - 1)[1].minor.@"?Form" = (yymsp - 1)[1].minor.@"Form"; // F-overwrites-V
// #line 1185 src/edn/edn.zig
        },
        6, // form ::= set
        => {
// #line 0 src/edn/edn.zy
            // #line 241 src/edn/edn.zy

            (yymsp - 1)[1].minor.@"?Form" = (yymsp - 1)[1].minor.@"Form"; // F-overwrites-S
// #line 1194 src/edn/edn.zig
        },
        7, // form ::= tagged
        => {
// #line 0 src/edn/edn.zy
            // #line 245 src/edn/edn.zy

            (yymsp - 1)[1].minor.@"?Form" = (yymsp - 1)[1].minor.@"Form"; // F-overwrites-T
// #line 1203 src/edn/edn.zig
        },
        8, // form ::= atom
        => {
// #line 0 src/edn/edn.zy
            // #line 249 src/edn/edn.zy

            (yymsp - 1)[1].minor.@"?Form" = (yymsp - 1)[1].minor.@"Form"; // F-overwrites-A
// #line 1212 src/edn/edn.zig
        },
        9, // form ::= discard
        => {
// #line 0 src/edn/edn.zy
            // #line 253 src/edn/edn.zy

            (yymsp - 1)[1].minor.@"?Form" = (yymsp - 1)[1].minor.@"?Form"; // F-overwrites-D
// #line 1221 src/edn/edn.zig
        },
        10, // list ::= PAL l_forms PAR
        => {
// #line 0 src/edn/edn.zy
            // #line 258 src/edn/edn.zy

            (yymsp - 3)[1].minor.@"Form" = Form.new((yymsp - 2)[1].minor.@"?*FormCons");
// #line 1230 src/edn/edn.zig
        },
        11, // list ::= PAL PAR
        => {
// #line 0 src/edn/edn.zy
            // #line 262 src/edn/edn.zy

            (yymsp - 2)[1].minor.@"Form" = Form.new(null);
// #line 1239 src/edn/edn.zig
        },
        12, // map ::= CRL pairs CRR
        => {
// #line 0 src/edn/edn.zy
            // #line 266 src/edn/edn.zy

            (yymsp - 3)[1].minor.@"Form" = Form.new((yymsp - 2)[1].minor.@"*Map");
// #line 1248 src/edn/edn.zig
        },
        13, // map ::= CRL CRR
        => {
// #line 0 src/edn/edn.zy
            // #line 270 src/edn/edn.zy

            const map = try allocator.create(Map);
            map.* = .empty;
            (yymsp - 2)[1].minor.@"Form" = Form.new(map);
// #line 1259 src/edn/edn.zig
        },
        14, // vector ::= SQL v_forms SQR
        => {
// #line 0 src/edn/edn.zy
            // #line 276 src/edn/edn.zy

            (yymsp - 3)[1].minor.@"Form" = Form.new((yymsp - 2)[1].minor.@"*Vector");
// #line 1268 src/edn/edn.zig
        },
        15, // vector ::= SQL SQR
        => {
// #line 0 src/edn/edn.zy
            // #line 280 src/edn/edn.zy

            const vec = try allocator.create(Vector);
            vec.* = .empty;
            (yymsp - 2)[1].minor.@"Form" = Form.new(vec);
// #line 1279 src/edn/edn.zig
        },
        16, // set ::= LSET s_forms CRR
        => {
// #line 0 src/edn/edn.zy
            // #line 286 src/edn/edn.zy

            (yymsp - 3)[1].minor.@"Form" = Form.new((yymsp - 2)[1].minor.@"*Set");
// #line 1288 src/edn/edn.zig
        },
        17, // set ::= LSET CRR
        => {
// #line 0 src/edn/edn.zy
            // #line 290 src/edn/edn.zy

            const set = try allocator.create(Set);
            set.* = .empty;
            (yymsp - 2)[1].minor.@"Form" = Form.new(set);
// #line 1299 src/edn/edn.zig
        },
        18, // tagged ::= TAGGED t_form
        => {
// #line 0 src/edn/edn.zy
            // #line 296 src/edn/edn.zy

            const tag = try Tagged.new(allocator, &(yymsp - 2)[1].minor.@"Token", &(yymsp - 1)[1].minor.@"Form");
            (yymsp - 2)[1].minor.@"Form" = Form.new(tag);
            // F-overwrites-T
// #line 1310 src/edn/edn.zig
        },
        19, // tagged ::= TAGGED discard t_form
        => {
            defer yy_destructor(yypParser,29,&(yymsp - 2)[1].minor);
// #line 0 src/edn/edn.zy
            // #line 302 src/edn/edn.zy

            const tag = try Tagged.new(allocator, &(yymsp - 3)[1].minor.@"Token", &(yymsp - 1)[1].minor.@"Form");
            (yymsp - 3)[1].minor.@"Form" = Form.new(tag);
            // F-overwrites-T
// #line 1322 src/edn/edn.zig
        },
        20, // discard ::= DISCARD form
        => {
// #line 0 src/edn/edn.zy
            // #line 308 src/edn/edn.zy

            if ((yymsp - 1)[1].minor.@"?Form") |form| form.deinit(allocator);
            (yymsp - 2)[1].minor.@"?Form" = null;
// #line 1332 src/edn/edn.zig
        },
        21, // l_forms ::= form l_forms
        => {
// #line 0 src/edn/edn.zy
            // #line 313 src/edn/edn.zy

            if ((yymsp - 2)[1].minor.@"?Form") |form| {
            yylhsminor.@"?*FormCons" = try FormCons.create(allocator, form);
            yylhsminor.@"?*FormCons".?.cons((yymsp - 1)[1].minor.@"?*FormCons");
            } else {
            yylhsminor.@"?*FormCons" = (yymsp - 1)[1].minor.@"?*FormCons";
            }
// #line 1346 src/edn/edn.zig
            (yymsp - 2)[1].minor.@"?*FormCons" = yylhsminor.@"?*FormCons";
        },
        22, // l_forms ::= form
        => {
// #line 0 src/edn/edn.zy
            // #line 322 src/edn/edn.zy

            if ((yymsp - 1)[1].minor.@"?Form") |form| {
            errdefer form.deinit(allocator);
            yylhsminor.@"?*FormCons" = try FormCons.create(allocator, form);
            } else {
            yylhsminor.@"?*FormCons" = null;
            }
// #line 1361 src/edn/edn.zig
            (yymsp - 1)[1].minor.@"?*FormCons" = yylhsminor.@"?*FormCons";
        },
        23, // v_forms ::= v_forms form
        => {
// #line 0 src/edn/edn.zy
            // #line 331 src/edn/edn.zy

            if ((yymsp - 1)[1].minor.@"?Form") |form| {
            errdefer form.deinit(allocator);
            try (yymsp - 2)[1].minor.@"*Vector".append(allocator, form);
            }
            (yymsp - 2)[1].minor.@"*Vector" = (yymsp - 2)[1].minor.@"*Vector";
            // V-overwrites-Vlist
// #line 1376 src/edn/edn.zig
        },
        24, // v_forms ::= form
        => {
// #line 0 src/edn/edn.zy
            // #line 340 src/edn/edn.zy

            errdefer if ((yymsp - 1)[1].minor.@"?Form") |form| form.deinit(allocator);
            yylhsminor.@"*Vector" = try allocator.create(Vector);
            yylhsminor.@"*Vector".* = .empty;
            if ((yymsp - 1)[1].minor.@"?Form") |form| {
            try yylhsminor.@"*Vector".append(allocator, form);
            }
// #line 1390 src/edn/edn.zig
            (yymsp - 1)[1].minor.@"*Vector" = yylhsminor.@"*Vector";
        },
        25, // pairs ::= pairs pair
        => {
// #line 0 src/edn/edn.zy
            // #line 349 src/edn/edn.zy

            if ((yymsp - 1)[1].minor.@"?*Pair") |pair| {
            errdefer pair.destroy(allocator);
            if (try (yymsp - 2)[1].minor.@"*Map".fetchPut(allocator, pair.key, pair.value)) |kv| {
            kv.key.deinit(allocator);
            kv.value.deinit(allocator);
            }
            allocator.destroy(pair);
            }
            yylhsminor.@"*Map" = (yymsp - 2)[1].minor.@"*Map";
// #line 1408 src/edn/edn.zig
            (yymsp - 2)[1].minor.@"*Map" = yylhsminor.@"*Map";
        },
        26, // pairs ::= pair
        => {
// #line 0 src/edn/edn.zy
            // #line 361 src/edn/edn.zy

            errdefer if ((yymsp - 1)[1].minor.@"?*Pair") |pair| pair.destroy(allocator);
            const map = try allocator.create(Map);
            map.* = .empty;
            if ((yymsp - 1)[1].minor.@"?*Pair") |pair| {
            try map.put(allocator, pair.key, pair.value);
            allocator.destroy(pair);
            }
            yylhsminor.@"*Map" = map;
// #line 1425 src/edn/edn.zig
            (yymsp - 1)[1].minor.@"*Map" = yylhsminor.@"*Map";
        },
        27, // pair ::= m_form m_form
        => {
// #line 0 src/edn/edn.zy
            // #line 372 src/edn/edn.zy

            yylhsminor.@"?*Pair" = try Pair.create(allocator, (yymsp - 2)[1].minor.@"Form", (yymsp - 1)[1].minor.@"Form");
// #line 1435 src/edn/edn.zig
            (yymsp - 2)[1].minor.@"?*Pair" = yylhsminor.@"?*Pair";
        },
        28, // pair ::= m_form discard m_form
        => {
            defer yy_destructor(yypParser,29,&(yymsp - 2)[1].minor);
// #line 0 src/edn/edn.zy
            // #line 376 src/edn/edn.zy

            yylhsminor.@"?*Pair" = try Pair.create(allocator, (yymsp - 3)[1].minor.@"Form", (yymsp - 1)[1].minor.@"Form");
// #line 1446 src/edn/edn.zig
            (yymsp - 3)[1].minor.@"?*Pair" = yylhsminor.@"?*Pair";
        },
        29, // pair ::= discard
        => {
            yy_destructor(yypParser,29,&(yymsp - 1)[1].minor);
// #line 0 src/edn/edn.zy
            // #line 380 src/edn/edn.zy

            (yymsp - 1)[1].minor.@"?*Pair" = null;
// #line 1457 src/edn/edn.zig
        },
        30, // s_forms ::= s_forms form
        => {
// #line 0 src/edn/edn.zy
            // #line 384 src/edn/edn.zy

            if ((yymsp - 1)[1].minor.@"?Form") |form| {
            errdefer form.deinit(allocator);
            if (try (yymsp - 2)[1].minor.@"*Set".fetchPut(allocator, form, {})) |entry| {
            entry.key.deinit(allocator);
            }
            }
            yylhsminor.@"*Set" = (yymsp - 2)[1].minor.@"*Set";
// #line 1472 src/edn/edn.zig
            (yymsp - 2)[1].minor.@"*Set" = yylhsminor.@"*Set";
        },
        31, // s_forms ::= form
        => {
// #line 0 src/edn/edn.zy
            // #line 394 src/edn/edn.zy

            const set = try allocator.create(Set);
            set.* = .empty;
            if ((yymsp - 1)[1].minor.@"?Form") |form| {
            errdefer form.deinit(allocator);
            try set.put(allocator, form, {});
            }
            yylhsminor.@"*Set" = set;
// #line 1488 src/edn/edn.zig
            (yymsp - 1)[1].minor.@"*Set" = yylhsminor.@"*Set";
        },
        32, // atom ::= SYMBOL
        => {
// #line 0 src/edn/edn.zy
            // #line 404 src/edn/edn.zy

            const atom = try Atom.new((yymsp - 1)[1].minor.@"Token", allocator);
            yylhsminor.@"Form" = Form.new(atom);
// #line 1499 src/edn/edn.zig
            (yymsp - 1)[1].minor.@"Form" = yylhsminor.@"Form";
        },
        33, // atom ::= NUMBER
        => {
// #line 0 src/edn/edn.zy
            // #line 409 src/edn/edn.zy

            const atom = try Atom.new((yymsp - 1)[1].minor.@"Token", allocator);
            yylhsminor.@"Form" = Form.new(atom);
// #line 1510 src/edn/edn.zig
            (yymsp - 1)[1].minor.@"Form" = yylhsminor.@"Form";
        },
        34, // atom ::= STRING
        => {
// #line 0 src/edn/edn.zy
            // #line 414 src/edn/edn.zy

            const atom = try Atom.new((yymsp - 1)[1].minor.@"Token", allocator);
            yylhsminor.@"Form" = Form.new(atom);
// #line 1521 src/edn/edn.zig
            (yymsp - 1)[1].minor.@"Form" = yylhsminor.@"Form";
        },
        35, // atom ::= KEYWORD
        => {
// #line 0 src/edn/edn.zy
            // #line 419 src/edn/edn.zy

            const atom = try Atom.new((yymsp - 1)[1].minor.@"Token", allocator);
            yylhsminor.@"Form" = Form.new(atom);
// #line 1532 src/edn/edn.zig
            (yymsp - 1)[1].minor.@"Form" = yylhsminor.@"Form";
        },
        36, // atom ::= CHARACTER
        => {
// #line 0 src/edn/edn.zy
            // #line 424 src/edn/edn.zy

            const atom = try Atom.new((yymsp - 1)[1].minor.@"Token", allocator);
            yylhsminor.@"Form" = Form.new(atom);
// #line 1543 src/edn/edn.zig
            (yymsp - 1)[1].minor.@"Form" = yylhsminor.@"Form";
        },
        37, // atom ::= NIL
        => {
// #line 0 src/edn/edn.zy
            // #line 429 src/edn/edn.zy

            const atom = try Atom.new((yymsp - 1)[1].minor.@"Token", allocator);
            yylhsminor.@"Form" = Form.new(atom);
// #line 1554 src/edn/edn.zig
            (yymsp - 1)[1].minor.@"Form" = yylhsminor.@"Form";
        },
        38, // atom ::= TRUE|FALSE
        => {
// #line 0 src/edn/edn.zy
            // #line 434 src/edn/edn.zy

            const atom = try Atom.new((yymsp - 1)[1].minor.@"Token", allocator);
            yylhsminor.@"Form" = Form.new(atom);
// #line 1565 src/edn/edn.zig
            (yymsp - 1)[1].minor.@"Form" = yylhsminor.@"Form";
        },
        else => {
            yy_assert(yyruleno != 39); // (39) m_form ::= list (OPTIMIZED OUT)
            yy_assert(yyruleno != 40); // (40) m_form ::= map (OPTIMIZED OUT)
            yy_assert(yyruleno != 41); // (41) m_form ::= vector (OPTIMIZED OUT)
            yy_assert(yyruleno != 42); // (42) m_form ::= set (OPTIMIZED OUT)
            yy_assert(yyruleno != 43); // (43) m_form ::= tagged (OPTIMIZED OUT)
            yy_assert(yyruleno != 44); // (44) m_form ::= atom (OPTIMIZED OUT)
            yy_assert(yyruleno != 45); // (45) t_form ::= list (OPTIMIZED OUT)
            yy_assert(yyruleno != 46); // (46) t_form ::= map (OPTIMIZED OUT)
            yy_assert(yyruleno != 47); // (47) t_form ::= vector (OPTIMIZED OUT)
            yy_assert(yyruleno != 48); // (48) t_form ::= set (OPTIMIZED OUT)
            yy_assert(yyruleno != 49); // (49) t_form ::= atom (OPTIMIZED OUT)
        },
//********* End reduce actions ************************************************/
    }
    yy_assert(yyruleno < yyRuleInfoLhs.len);
    const yygoto = yyRuleInfoLhs[yyruleno];
    const yyact = yy_find_reduce_action((yymsp - @abs(yysize))[0].stateno, yygoto);

    // There are no SHIFTREDUCE actions on nonterminals because the table
    // generator has simplified them to pure REDUCE actions.
    yy_assert(!(yyact > YY_MAX_SHIFT and yyact <= YY_MAX_SHIFTREDUCE));

    // It is not possible for a REDUCE to be followed by an error
    yy_assert(yyact != YY_ERROR_ACTION);

    yymsp = yymsp + 1 - @abs(yysize);
    yypParser.tos = yymsp;
    yymsp[0].stateno = yyact;
    yymsp[0].major = yygoto;
    yyTraceShift(yypParser, yyact, "... then shift");
    return yyact;
}

/// The following code executes when the parse fails
fn yy_parse_failed(
    /// The parser
    yypParser: *Parser,
) !void {

    var result = yypParser.result; _ = .{&result};
    defer {

        yypParser.result = result;
    }
    const allocator = yypParser.allocator; _ = .{allocator};
    // #ifndef NDEBUG
    //   if( yyTraceFILE ){
    //     fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
    //   }
    // #endif
    while (@intFromPtr(yypParser.tos) > @intFromPtr(yypParser.stack))
        yy_pop_parser_stack(yypParser);
    // Here code is inserted which will be executed whenever the
    // parser fails.
    { // Throw guard
//*********** Begin %parse_failure code ***************************************/
//*********** End %parse_failure code *****************************************/
    }
}

/// The following code executes when a syntax error first occurs.
fn yy_syntax_error(
    /// The parser */
    yypParser: *Parser,
    /// The major type of the error token */
    yymajor: YYCODETYPE,
    /// The minor type of the error token */
    yyminor: YY_TOKEN_TYPE,
) !void {

    var result = yypParser.result; _ = .{&result};
    defer {

        yypParser.result = result;
    }
    const err_token = yyminor;
    const allocator = yypParser.allocator;
    _ = .{ err_token, yymajor, allocator };
    {
//*********** Begin %syntax_error code ****************************************/
//*********** End %syntax_error code ******************************************/
    }
}

/// The following is executed when the parser accepts
fn yy_accept(
    /// The parser
    yypParser: *Parser,
) !void {

    var result = yypParser.result; _ = .{&result};
    defer {

        yypParser.result = result;
    }
    const allocator = yypParser.allocator; _ = .{allocator};
    if (comptime !NDEBUG) {

    }
    // #ifndef NDEBUG
    //   if( yyTraceFILE ){
    //     fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
    //   }
    // #endif
    if (comptime YYNOERRORRECOVERY) {
        yypParser.errcnt = -1;
    }
    yy_assert(yypParser.tos == yypParser.stack);
    // Here code is inserted which will be executed whenever the
    // parser accepts.
    {
//********** Begin %parse_accept code *****************************************/
//********** End %parse_accept code *******************************************/
    }
}

/// Cast the token number to its affiliated enum
inline fn yyEnum(yymajor: YYCODETYPE) TokenKind {
    return @enumFromInt(yymajor);
}

// TODO: This could return the context when there is one, and
// `void` otherwise.  That wouldn't be excessively tricksy to
// code up.
//
/// The main parser program.
/// The first argument is a pointer to a structure obtained from
/// "ParseAlloc" which describes the current state of the parser.
/// The second argument is the major token number.  The third is
/// the minor token.  The fourth optional argument is whatever the
/// user wants (and specified in the grammar) and is available for
/// use by the action routines.
///
/// - Inputs:
///
///   - A pointer to the parser (an opaque structure.)
///   - The major token number.
///   - The minor token number.
///   - An option argument of a grammar-specified type.
///
/// - Outputs:
///
///   - None.
///
fn yyParse(
    /// The parser
    yypParser: *Parser,
    /// The major token enum
    yy_token: TokenKind,
    /// The value for the token
    yyminor: YY_TOKEN_TYPE
                   // Optional %extra_argument parameter
) !void {
    var yyminorunion: YYMINORTYPE = undefined;
    var yyact: YYACTIONTYPE = undefined;   // The parser action.
    var yyendofinput: bool = false;
    var yyerrorhit: bool = false;
    // Enum integer type is user-configurable, but Zitron counts everything
    // and uses that number to determine internal integer widths.  So this
    // cast cannot fail.
    const yymajor: YYCODETYPE = @intCast(@intFromEnum(yy_token));

    if (comptime (!YYHAS_ERRORSYMBOL and !YYNOERRORRECOVERY)) {
        yyendofinput = (yymajor==0);
    }
    yyact = yypParser.tos[0].stateno;

    if (comptime !NDEBUG) {

    }

    resolve: while (true) { // Exit by "break"
        yy_assert(@intFromPtr(yypParser.tos) >= @intFromPtr(yypParser.stack));
        yy_assert(yyact == yypParser.tos[0].stateno);
        yyact = yy_find_shift_action(yymajor, yyact);
        if( yyact >= YY_MIN_REDUCE ){
            const yyruleno = yyact - YY_MIN_REDUCE; // Reduce by this rule
            yy_assert(yyruleno < yyRuleName.len);
            if (comptime !NDEBUG) {

            }
            // Check that the stack is large enough to grow by a single entry
            // if the RHS of the rule is empty.  This ensures that there is room
            // enough on the stack to push the LHS value.
            if (yyRuleInfoNRhs[yyruleno] == 0) {
                // if ((comptime YYTRACKMAXSTACKDEPTH))
                // and (yypParser.tos - yypParser.stack) > yypParser.yyhwm)
                // {
                //     yypParser.yyhwm += 1;
                //     yy_assert(yypParser.yyhwm == yypParser.yytos - yypParser.yystack);
                // }
                if (@intFromPtr(yypParser.tos) >= @intFromPtr(yypParser.stack_end)) {
                    yyGrowStack(yypParser) catch {
                        try yyStackOverflow(yypParser);
                        break :resolve;
                    };
                }
            }
            yyact = try yy_reduce(yypParser, yyruleno, yymajor, yyminor);
        } else if (yyact <= YY_MAX_SHIFTREDUCE) {
            try yy_shift(yypParser, yyact, yymajor, yyminor);
            if (comptime !YYNOERRORRECOVERY) {
                yypParser.errcnt -= 1;
            }
            break :resolve;
        } else if (yyact == YY_ACCEPT_ACTION) {
            yypParser.tos -= 1;
            try yy_accept(yypParser);
            return;
        } else {
            yy_assert( yyact == YY_ERROR_ACTION );
            yyminorunion = .{.@"Token" = yyminor};
            if (comptime !NDEBUG) {

            }
            // A syntax error has occurred.
            // The response to an error depends upon whether or not the
            // grammar defines an error token "ERROR".
            //
            if (comptime YYHAS_ERRORSYMBOL) {
                // This is what we do if the grammar does define ERROR:
                //
                //  * Call the %syntax_error function.
                //
                //  * Begin popping the stack until we enter a state where
                //    it is legal to shift the error symbol, then shift
                //    the error symbol.
                //
                //  * Set the error count to three.
                //
                //  * Begin accepting and shifting new tokens.  No new error
                //    processing will occur until three tokens have been
                //    shifted successfully.
                //
                //
                if (yypParser.errcnt < 0) {
                    try yy_syntax_error(yypParser, yymajor, yyminor);
                }
                const yymx = yypParser.tos[0].major;
                if ((yymx == @This().YYERRORSYMBOL) or yyerrorhit) {
                    if (comptime !NDEBUG) {

                    }
                    yy_destructor(yypParser, yymajor, &yyminorunion);
                    yymajor = YYNOCODE;
                } else {
                    while (yypParser.tos > yypParser.stack) {
                        yyact = yy_find_reduce_action(yypParser.tos[0].stateno, @This().YYERRORSYMBOL);
                        if (yyact <= YY_MAX_SHIFTREDUCE) break;
                        yy_pop_parser_stack(yypParser);
                    }
                    if (yypParser.tos <= yypParser.stack or yymajor == 0) {
                        yy_destructor(yypParser, yymajor, &yyminorunion);
                        try yy_parse_failed(yypParser);
                        if (comptime !YYNOERRORRECOVERY) {
                            yypParser.yyerrcnt = null;
                        }
                        yymajor = YYNOCODE;
                    } else if (yymx != @This().YYERRORSYMBOL) {
                        try yy_shift(yypParser, yyact, @This().YYERRORSYMBOL, yyminor);
                    }
                }
                yypParser.errcnt = 3;
                yyerrorhit = true;
                if (yymajor == YYNOCODE) break;
                yyact = yypParser.tos[0].stateno;
            } else if (comptime YYNOERRORRECOVERY) {
                // If the YYNOERRORRECOVERY macro is defined, then do not attempt to
                // do any kind of error recovery.  Instead, simply invoke the syntax
                // error routine and continue going as if nothing had happened.
                //
                // Applications can set this macro (for example inside %include) if
                // they intend to abandon the parse upon the first syntax error seen.
                //
                defer yy_destructor(yypParser, yymajor, &yyminorunion);
                try yy_syntax_error(yypParser, yymajor, yyminor);
                break :resolve;
            } else { // YYERRORSYMBOL is not defined, nor YYNOERRORRECOVERY
                // This is what we do if the grammar does not define ERROR:
                //
                //  * Report an error message, and throw away the input token.
                //
                //  * If the input token is $, then fail the parse.
                //
                // As before, subsequent error messages are suppressed until
                // three input tokens have been successfully shifted.
                //
                if (yypParser.errcnt <= 0) {
                    try yy_syntax_error(yypParser, yymajor, yyminor);
                }
                yypParser.errcnt = 3;
                yy_destructor(yypParser, yymajor, &yyminorunion);
                if( yyendofinput ){
                    try yy_parse_failed(yypParser);
                    if (comptime !YYNOERRORRECOVERY) {
                          yypParser.errcnt = -1;
                    }
                }
                break :resolve;
            }
        }
    }
    if (!NDEBUG) {

    }
    return;
}

// zig fmt: on

//********************* Home of %code blocks **********************************
// #line 439 src/edn/edn.zy

const OhSnap = @import("ohsnap");

fn snapTest(snap: OhSnap.Snap, string: [:0]const u8) !void {
    const allocator = std.testing.allocator;
    const result: ParseContext = undefined;
    var parser = try Parser.create(allocator, result);
    defer parser.destroy();
    defer parser.result.deinit(allocator);
    var tok = Tokenizer.init(string);
    while (try tok.next()) |t| {
        try parser.parse(t.kind, t);
    } else {
        try parser.finalize();
    }
    try snap.expectEqualFmt(parser.result);
}

test "List atoms" {
    const oh: OhSnap = .{};
    const list_atoms = oh.snap(
        @src(),
        \\(foo, :bar, "baz", 12, 4.2)
        \\
        ,
    );
    const list_str =
        \\(foo :bar "baz" 12 #_23 4.2)
    ;
    try snapTest(list_atoms, list_str);
}

test "map" {
    const oh: OhSnap = .{};
    const map_atoms = oh.snap(
        @src(),
        \\{ foo :bar  "baz" 12  4.2 [yo yoo yo] }
        \\
        ,
    );
    const map_str =
        \\{foo :bar ,"baz" 12 #_23 4.2 [yo yoo yo] #_:junk}
    ;
    try snapTest(map_atoms, map_str);
}

test "char" {
    const oh: OhSnap = .{};
    const char_atoms = oh.snap(
        @src(),
        \\(%, '\t', '∅', 'ሴ', '\n', '\')
        \\
        ,
    );
    const char_str =
        \\(% \tab \∅ \u1234 \newline \\)
    ;
    try snapTest(char_atoms, char_str);
}

test "parse list" {
    if (true) return;

    const allocator = std.testing.allocator;
    const result: ParseContext = undefined;
    var parser = try Parser.create(allocator, result);
    defer parser.destroy();
    defer parser.result.deinit(allocator);
    var tok = Tokenizer.init(
        \\   (foo bar baz () #_12 true)
        \\   (quux #_:crux :quuux "quuuux")
        \\   {k1 #_toss :v1, #_toss k2 "v2" #_toss} {}
        \\   #{ :moe, "curly" larry #_shemp } #{}
        \\   [2 4 6.0 :eight] []
        \\   #tag/thing #_:bye :thing #tag_1 12e7
        \\   nil
    );
    while (try tok.next()) |t| {
        try parser.parse(t.kind, t);
    } else {
        try parser.finalize();
    }
    std.debug.print("{f}", .{parser.result});
}

// #line 1965 src/edn/edn.zig
